### ISSUE TITLE
Wormtown removal request

### ISSUE THREAD

**Issue by Smxrez** [wwwDayDream/CessilCellsCeaChells#68]
Any chance you could remove the mod from the LastTrainOuttaWormtown community
Its a very very small community and we dont really have any purpose for it so it can kinda be annoying having it flood the mod releases channel

**Comment by wwwDayDream** [comment]
I'm in the discord linked on [Thunderstore](https://thunderstore.io/c/last-train-outta-wormtown/) and have had no issues reported to me. Additionally there is no channel in that discord that hosts the webhook so if it's a different server from "Last Discord Outta' Wormtown" then you may want to reach out to Thunderstore about having your discord linked correctly if it represents the modding community.

Additionally, I've taken steps today to reduce updates but it's a bit silly for me as a utility to stop supporting a game I plan on making mods because I'm actively updating it.
